-- AlterTable
ALTER TABLE `usuario` MODIFY `calleNumero` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `ciudad` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `codigoPostal` INTEGER NOT NULL DEFAULT 0,
    MODIFY `colonia` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `estado` VARCHAR(191) NOT NULL DEFAULT '';
